### ISSUE TITLE
Dashboard UI tidy up & layout

### ISSUE THREAD

**Issue by soyapark-kaist** [soyapark-kaist/data-petition#21]
At a current dashboard, different components spread out. It needs to be located closely and uniformly

**Comment by todoaskit** [comment]
Do we use `.chartbuilder-container`?

It has a dependency in react, which means we might need to use react to low level API.

Also, there can be some css compatibility issue.

**Comment by soyapark-kaist** [comment]
Yup. Im using chartbuilder and react in order to build chart builder.

**Comment by todoaskit** [comment]
OK, great.

Before I commit, I might want to put a disclaimer: there can be some unexpectable css side effect, and I have no ability to fix them by inspecting react components...

**Comment by soyapark-kaist** [comment]
We can save more space if we put x-axis and y-axis close to the chart 

![image](https://user-images.githubusercontent.com/25434849/44301392-cae3c200-a2e3-11e8-8c31-29f134aa353c.png)
